name: windows-2022

on:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/windows-2022.yml

jobs:
  vagrant:
    runs-on: windows-2022


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pybugz
        run: python -m pip install git+https://github.com/williamh/pybugz.git
      - run: bugz --version
      - uses: cygwin/cygwin-install-action@master
        with:
          packages: "wget, gcc-g++"

      - run: bash -c "bugz --version"
